### ISSUE TITLE
Fnet decompression issue 

### ISSUE THREAD

**Issue by ilobb** [HenriquesLab/ZeroCostDL4Mic#11]
Hello, me again!

I have successfully used U-net, Stardist and fnet notebooks using the example training and test datasets. I have found them to be a really useful utility. 

I have now moved on to using fnet for some of my own data. Specifically, I have phase contrast images of cells along with matched fluorescent staining of nuclei. I want to train a model such that I can detect nuclei and do cell counts on unstained images. 

In Section 4.1 "Train a new model", I get the following error. 

![image](https://user-images.githubusercontent.com/62608092/80119730-fc656400-8581-11ea-8809-ffea5368241c.png)

I presume this might be a result of the fact that the phase images are 8-bit grayscale TIFF and the fluorescence images are 16-bit grayscale TIFFs, as these seem to be the only allowable export formats from my instrument (Incucyte Zoom). If so I suppose I could look into converting?

Would you be able to comment?

Desktop:
 - OS: Windows 10 Enterprise
 - Browser chrome
 - Version 81.0.4044.122 (Official Build) (64-bit)

Thanks very much,

Ian

**Comment by guijacquemet** [comment]
Hi Ian,
Many thanks for reaching out!
I am tagging here @lucpaul who is our fnet expert and I am sure he will be able to help you out very soon! But indeed fnet as some very specific data requirement.
All the best
Guillaume

**Comment by lucpaul** [comment]
Hi Ian, thanks for asking the question,
I suspect that this error is an issue with the tifffile module that we install in this cell. As you said, I would first suggest, you adapt the data before getting specifically into changing the tifffile module.
How does that work out?
Next, we could have a look if we need to change the tifffile version or if any other modules might be needed to make it work on your data. Here is another thread where this is discussed https://github.com/scikit-image/scikit-image/issues/4326
Have a look if that could help.
But let me know if things work if you change the datatype. Otherwise, it might be necessary to get a different version of tifffile and adapt the code slightly.

**Comment by ilobb** [comment]
Hello,

Firstly, as ever, thank you both very much for all your help.

I did some playing around and converting both the file type to 8 bit TIFFs seemed to work in the respect that the error posted above no longer occurred. However I came across a different error which is more to do with my strategy rather than with the notebook _per se_. Namely, I was using single plane images rather than the multiple z-stacks required, thus the algorithm was not able to proceed.

I see you have another user asking about using single plane images for nuclei segmentation. I was going to use U-net for this as this seems like a better strategy going forward.
