### ISSUE TITLE
Single plane label-free prediction (fnet)

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#12]
Hi,

I am interested in predicting the position of nuclei from single plane bright-field images using fnet.
However, according to the documentation " [...] Stacks with fewer than 32 slices will only successfully train the model when they contain 16, 8 or 4 slices and other values will throw a tensordimensions error. [...]".

But is there a trick to convert a single plane into a synthetic 3D stack and make fnet work? Gaussian blur on Z axis?

The final aim being to be able to do nuclei segmentation and tracking from brightfield or phase contrast instead of fluorescence.

Thank you

**Comment by LPUoO** [comment]
I tried training the model with the sample data where I only kept the 10th slice and added 3 empty slices (white background for source and black background for target). The idea being to simulate a single plane image and adding 3 blank slices.

I also tried duplicating the 10th slice of the sample data into a 4-slice stack. (4 identical slices).


In both cases I get this error in 4.1 (trainning):
`
RuntimeError: Calculated padded input size per channel: (1 x 16 x 16). Kernel size: (2 x 2 x 2). Kernel size can't be greater than actual input size`

I'm unsure how to fix it ?

Thanks a lot

**Comment by guijacquemet** [comment]
Hi, 
Many thanks for reaching out!
If you want to segment nuclei from single plane bright-field images, I would instead try to train a UNET or a Stardist network. Both of these should work nicely on brightfield images. But you need to generate masks.
If you absolutely need to "artificially" label 2D brightfield images, then I would try CARE2D instead of fnet.
Let us know how it goes!
Cheers
Guillaume

**Comment by LPUoO** [comment]
Hello,
Thank you for the recommendation. I thought that using fnet for this purpose would be the easiest because one "only" needs matched images of DAPI and brighfield rather than manually annotated images.

Thanks !

**Comment by guijacquemet** [comment]
Hello,
If you already have brightfield images and matching nuclei, I would use an existing Stardist model to help you create the nuclei masks. This will not be perfect but you can manually correct the mistakes (rather than doing the annotation from scratch by hand). Once you have the masks, you can use them to train stardist on the brightfield images.
Cheers
Guillaume
