### ISSUE TITLE
error when running U-Net_2D_ZeroCostDL4Mic_BioImageModelZoo_export

### ISSUE THREAD

**Issue by angcriswell** [HenriquesLab/ZeroCostDL4Mic#163]
I am running the U-Net 2D notebook using the provided membrane test data set on Windows. I repeatedly get an error on step 5.2. This happens when I run any U-Net 2D notebook. The error is below and appears like files are not located because they written to a different directory. I wish I knew python a bit better to fix...

Model input size: 512x512
Number of dataset found in the folder: 30

100%
30/30 [00:02<00:00, 13.98it/s]

Running QC on: 8.png

FileNotFoundError Traceback (most recent call last)

in ()
52 print('Running QC on: '+filename)
53 test_input = io.imread(os.path.join(Source_QC_folder, filename), as_gray=True)
---> 54 test_ground_truth_image = io.imread(os.path.join(Target_QC_folder, filename), as_gray=True)
55
56 (threshold_list, iou_scores_per_threshold) = getIoUvsThreshold(os.path.join(prediction_QC_folder, prediction_prefix+filename), os.path.join(Target_QC_folder, filename))

6 frames

/usr/local/lib/python3.7/dist-packages/imageio/core/request.py in _parse_uri(self, uri)
381 # Reading: check that the file exists (but is allowed a dir)
382 if not os.path.exists(fn):
--> 383 raise FileNotFoundError("No such file: '%s'" % fn)
384 else:
385 # Writing: check that the directory to write to does exist

FileNotFoundError: No such file: '/content/gdrive/MyDrive/Data/membrane/membrane-model/Quality Control/Prediction/8.png'

**Comment by esgomezm** [comment]
hi @angcriswell 

Thank you for giving it a try. I think it is writing tiff files rather than png (which is the format used in the trainin&test data) and that is why it does not find the file. 

Could you please confirm that you have the 8.tiff file in the prediction folder? The path would be `'/content/gdrive/MyDrive/Data/membrane/membrane-model/Quality Control/Prediction/8.tif'`.

Thank you!

**Comment by angcriswell** [comment]
Hi,

In  /Data/membrane/membrane-model/Quality Control/Prediction I do have a
file named Prediction_8.tif. All predictions have Prediction_#.tif.

Is there something I can change in the notebook to correct the error?

Best,
Angela

**Comment by esgomezm** [comment]
I updated the notebook `U-Net_2D_ZeroCostDL4Mic_BioImageModelZoo_export.ipynb` in the [BioImage.io notebooks folder](https://github.com/HenriquesLab/ZeroCostDL4Mic/tree/master/Colab_notebooks/BioImage.io%20notebooks). It should work now. I changed the section 5.2 in the notebook so it looks for tif files in the prediction folder rather than png. The rest is the same. 

Please, let us know if it worked.

**Comment by esgomezm** [comment]
Sorry for that one. I've corrected it and the notebook is already available. If you want to change it manually, you can substitute `pretrained_model_path ` by `full_QC_model_path` in line 132.

**Comment by angcriswell** [comment]
Thanks so much @esgomezm!
