### ISSUE TITLE
Installation of fnet and dependencies 

### ISSUE THREAD

**Issue by ilobb** [HenriquesLab/ZeroCostDL4Mic#2]
Hello all,
First time user of ZeroCostDL4Mic, and github for that matter. Please accept my apologies in advance for if is the wrong forum for such a query.

I have been trying to use the fnet notebook, guided by your YouTube video. I just wanted to run through the example data to get a feel for the set up. I can access a GPU and mount my google drive without any problems. However, I am running into problems when trying to install fnet and it's dependencies. 

Specifically I receive the following error:

![image](https://user-images.githubusercontent.com/62608092/77443992-5a682580-6de3-11ea-9675-175dd26c50eb.png)

Desktop:
 - OS: Windows 10 Enterprise
 - Browser Chrome
 
Any help would be greatly appreciated.

Cheers,
Ian

**Comment by lucpaul** [comment]
Hi Ian,
these errors show up but don't affect the training of the network. It may have to do with the fact that we are enforcing an older version of tensorflow to avoid issues when colab updates to tensorflow 2x and this might raise the flag in the notebook. But this usually doesn't affect the training.
If you play the subsequent cells, do you run into issues relating to these errors? If yes, can you send a screenshot? I hope this helps and you can get it to run. If not, let me know.

Thanks a lot for the comment.

Lucas

**Comment by ilobb** [comment]
Hi Lucas,
Thank you very much for the help. You are correct that it did not seem to effect the training. 
I had failed to get the training to run prior to making my comment, but I believe that was due to trying to run the training on the test, rather than training, dataset.

I have, however, encountered another problem with Section 4.2-"Training from a previously saved model". My understanding was that the "training_target" in this instance would be a training model, and therefore I entered "ftnettest", the name of my model, into this field. I kept the path  for the training source as previously. However, I keep getting an error message, see below:

![image](https://user-images.githubusercontent.com/62608092/77671208-2a558980-6f7f-11ea-87bc-20e89594c871.png)

I have tried changing the "training_source" and "training_target" to the paths of the datasets I originally used for training, and also just to these file names alone (given it explicitly states to give the name and not the path). However, I get a similar error message each time.

If you could offer any insight it would be most appreciate.
Thanks,
Ian

**Comment by lucpaul** [comment]
Hi Ian,
the target_folder should be a path, similar to when the model is initially trained. So it should not be the name of the model you are training but the folder path of a dataset with the targets to your sources, usually the same datasets you trained with originally (as you assumed).
If you still encounter this problem after changing the inputs to those lines accordingly, I would recommend saving your trained model and getting rid of the pytorch_fnet folder (last cell). Then try this again by first playing cell 2 again and then moving straight to restart training with your model.

The statement with the 'name' instead of the 'path' is not relevant anymore, actually, I must have missed that. We will get rid of that in the next version. I agree that that must be confusing. Thanks for pointing this out.
I hope this helps and you can get ahead with your training. Apologies for any confusion. 

Also, if you encounter another unrelated problem, you can open this as a separate issue, so other people can find it more easily if they have the same problem.

Lucas

**Comment by lucpaul** [comment]
Quick update, the earlier comment might not quite work without replaying the cell in 3, too. I am having a look at this right now. So if you get errors when re-training try either training again from the start, including cell 3 or wait for the next release which should be before the weekend. 

In detail, the problem is that some of the files fnet depends on, including the csv files and training.sh, in the current version of the notebook don't have all the correct parameters if you only play 4.2. If you're keen to solve this yourself, you can try to copy some of the code from 3 into the first cell in 4.2. But in the next version, this will be updated and should not show the same errors.

**Comment by ilobb** [comment]
Hello again Lucas. Thanks so much for all your help. I waited a few days  for the updates and have now successfully run through the whole notebook without any problems. I will now look into using it for my own data rather than just the example data. Thanks again.
