### ISSUE TITLE
Stardist 2D -Fiji version 

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#20]
Hi,

What makes the Stardist 2D -Fiji version different from the "Normal" Stardist 2D version ?

Thanks

**Comment by guijacquemet** [comment]
Hello,
The stardist 2D -Fiji version allows you to export the model you model train so that you can use it in the Stardist Fiji plugin to do the predictions. In the "normal" Stardist 2D version the training and predictions are done directly in the notebook.
The two notebooks use a different version of TensorFlow to run so they may be small differences in term of performance.
Cheers
Guillaume

**Comment by SHaensch** [comment]
Hi,
a followup on that. Is there a way that the other notebooks can be used on fiji versions as well? E.g. Noise2Void?
Best
Sebastian

**Comment by guijacquemet** [comment]
Hi, 
yes, I could probably make other notebooks so that the trained network could be used in Fiji if it is useful. Probably not for all the notebooks (yet).  For instance, the CARE notebook should be possible. I cannot guaranty one for Noise2Void as I do not know if the Noise2Void networks work with the CSBdeep ImageJ plugin (I have not tested this yet). 
If you are interested in running (training + prediction) noise2VOID in Fiji, you could check https://forum.image.sc/t/noise2void-for-fiji/34552 
Cheers
Guillaume

**Comment by LPUoO** [comment]
Sorry, my initial question wasn't specific enough.
I thought that all the models created in the ZeroCostDL4Mic were already compatible with FIJI, using DeepImageJ.

[https://forum.image.sc/t/neubias-academy-home-webinar-machine-learning-deep-learning-deepimagej-questions-answers/36962](url)
```
Q50-1: Can I run any model generated in ZeroCostDL4Mic colab notebooks in DeepImageJ ?

DeepImageJ can run any TensorFlow models, until now only for image2image applications. So if you could save the ZeroCostDL4Mic model as TensorFlow, you will be able to use in DeepImageJ
```
Is this correct ?

Thank you

**Comment by guijacquemet** [comment]
Hi, 
Yes, potentially all/most of the models created in ZeroCostDL4Mic could be used in FIJI via DeepImageJ. However, in practice, this may require some tweaking and workaround. Unfortunately.  this is not something we had the chance to work/experiment with actively yet as our current main focus is to expend the training capabilities of ZeroCostDL4Mic. 
Most of the ZeroCostDL4Mic notebook uses tf1.15.2 so if you try to import them in DeepImageJ and it works please let us know!
Cheers
Guillaume
