### ISSUE TITLE
Question about training/validation error curves 

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#23]
Hi,
Question about about training/validation error curves found in the tips and trick page.
![image](https://user-images.githubusercontent.com/64419544/83363148-081d2500-a38f-11ea-9bae-3910031c2945.png)
![image](https://user-images.githubusercontent.com/64419544/83363162-18350480-a38f-11ea-9ecd-e35796d64e8f.png)
"By decreasing the number of patches significantly, we were able to prevent overfitting to the training dataset"
Does this mean that the same fragment of the image could be found in multiple patches ? And this is why it is overfitting ?

Thank you

**Comment by Romain-Laine** [comment]
Dear LPUoO, yes that's right. We think that it is exactly what had been happening in this occasion. Although, in general terms, there are other reasons why a model could be overfitting and this case is specific to how the patches are generated and used. I hope this helps !
Cheers,

Romain

**Comment by LPUoO** [comment]
Thank you,

So I guess that in general the best is to calculate how many patches are created from a given image for a given patch size and use that value?

For example if one image is 10x10 end we use a patch size of 2x2 we must use exactly 25 patches otherwise we risk to overfit the model.
![image](https://user-images.githubusercontent.com/64419544/83421167-8cb78400-a41f-11ea-9b30-866d4941f5c5.png)
Or do we some time want to use overlapping patches ?

Thanks a lot

**Comment by Romain-Laine** [comment]
Hi, in principle, it's a good rule of thumb, yes. But some minor overlap will likely happen before that since the actual position of the patches are chosen at random across the image (and not neatly arranged as you drew them). So, I would consider your rule of thumb as an upper limit of the number of patches to use !
In practice, the best is to try a range of number of patches and see what happens with your particular data.

I hope this helps !

Romain
