### ISSUE TITLE
YOLO V2 map_evaluation.py no such file or directory

### ISSUE THREAD

**Issue by rdemets** [HenriquesLab/ZeroCostDL4Mic#40]
Hi. 

I am trying to utilize your pipeline to train images on my local folder. I have slightly modified the code to find the correct path, but I am facing the same issue using the gdrive. I think that there is a missing file in the cloning. 

I am getting this error : 
FileNotFoundError: [Errno 2] No such file or directory: '/content/gdrive/My Drive/keras-yolo2/map_evalution.py'.

Indeed, the folder exists for the file is absent. 
![Screenshot 2020-08-17 at 18 21 07](https://user-images.githubusercontent.com/38579350/90385962-7502aa00-e0b6-11ea-9bea-c8eded6adcc5.jpg)

Thank you very much for your help. 
Regards, Richard

**Comment by lucpaul** [comment]
Hi Richard, thanks for trying the notebook.
first, could you explain which bits of the code you changed, so I can reproduce the error? That might help.

My suspicion for map_evaluation.py missing is that it's copied from a different branch of the github repo (found [here](https://github.com/rodrigo2019/keras_yolo2) ) than the rest of the notebook (which came from [here](https://github.com/experiencor/keras-yolo2) ), and I simply copied it separately to the keras-yolo2 folder. (The reason is that the mAP score wasn't tracked during training when using the original branch, so I added it separately from another one. ) The crucial bit in the code is here (in cell 2, near the top): 

![image](https://user-images.githubusercontent.com/39629039/90402665-b041b080-e097-11ea-9dea-d7d64c32ae56.png)

(Here, the source folder is the folder where map_evaluation.py comes from, the destination is the folder of the keras-yolo2 folder that is used for this notebook)
So, if you changed the path to your local folder make sure you copy the map_evaluation.py to where you need it, too. I hope this helps. Let me know how you're getting on!

Best,
Lucas
