### ISSUE TITLE
start training error

### ISSUE THREAD

**Issue by insectito** [HenriquesLab/ZeroCostDL4Mic#46]
Hi,
I'm trying to use de U-net training with the provided data, but in the step 4.2 the following error appears 
![image](https://user-images.githubusercontent.com/70763934/92399139-b1f41680-f121-11ea-8a07-40b6336b4ffe.png)
until this step everything was fine.
Can you help me to understand what's happening?

Thank you very much.

**Comment by lucpaul** [comment]
Thanks for your question,
can you give a few more details what parameters you were using for training? Also, did you make any code adjustments? It could also help to see the full error message. You could also check if the error repeats when you restart the runtime of the notebook and start the training again. 
If you can give us some of these details, we can hopefully reproduce the error and find out what's happening and fix this.

**Comment by guijacquemet** [comment]
Hi,
I uploaded a new version of the notebook. Could you let me know if you still have the same issue?
Thanks
Guillaume

**Comment by insectito** [comment]
Hi,

Thank you for your help, I have tried again but I had the same issue, here is the captures of what I have done. I skiped 3.2 and 3.3 and basically I left all the defaul settings and the input images are 8 bit, is this the issue?

![image](https://user-images.githubusercontent.com/70763934/93214610-4d5a3c80-f75d-11ea-873b-147bedfb2ece.png)
![image](https://user-images.githubusercontent.com/70763934/93214002-8219c400-f75c-11ea-8242-dd401e12d899.png)
![image](https://user-images.githubusercontent.com/70763934/93214146-b5f4e980-f75c-11ea-9d44-af52492275bb.png)
![image](https://user-images.githubusercontent.com/70763934/93214423-12580900-f75d-11ea-8b06-c99b949c7443.png)
![image](https://user-images.githubusercontent.com/70763934/93214528-3287c800-f75d-11ea-89d6-720112e2e3b3.png)

Thank you very much.

**Comment by guijacquemet** [comment]
Hi,
Could you confirm that you are using the latest version of the notebook? 
Also did you try running the notebook with the test data we provide?

**Comment by insectito** [comment]
Hi, 
Thanks, yes, I use it with the sample data and with the latest version of the notebook.
![image](https://user-images.githubusercontent.com/70763934/93247661-8e1a7b80-f786-11ea-9949-2fb5e3e763cd.png)
Thank you for your help

**Comment by guijacquemet** [comment]
Hi,
Just checking, are you running all the cells including the data augmentation and transfer learning cell ? (you can disable them by ticking the box but you will need to run the cell). For instance, the error you report occurs if the transfer learning cell is not ran.

**Comment by robgirod** [comment]
Hi,
First of all many thanks for your work on those notebooks. I'm jumping in because I am currently running in the same issue than described here by @insectito when running cell 4.2.
For details I have tried:
- with my own data and with the ISBI data obtained following the alternative method described in the wiki.
- with the latest notebook version (uploaded on september 13th) and older versions back to 1.3
- with and without running data augmentation and transfer learning cells and ticking/unticking them
- restarting the runtime
- using firefox and chrome

Unfortunately I don't know how to reproduce the error if you are not having it initially. I'm adding below screenshots of the whole cell output.

Thanks,
Robin

![image](https://user-images.githubusercontent.com/71637217/93783612-2f447e80-fc2c-11ea-8ab7-fa43b591df50.png)
![image](https://user-images.githubusercontent.com/71637217/93783660-3ec3c780-fc2c-11ea-8a45-cb91a78448d1.png)
![image](https://user-images.githubusercontent.com/71637217/93783684-497e5c80-fc2c-11ea-9857-5d5281a630c7.png)
![image](https://user-images.githubusercontent.com/71637217/93783713-526f2e00-fc2c-11ea-800c-04eb04416555.png)

**Comment by robgirod** [comment]
Awesome, works a treat now! Thank you!

**Comment by guijacquemet** [comment]
Thanks for testing and getting back to me!
Cheers

Guillaume
