### ISSUE TITLE
Out of RAM in N2V 2D

### ISSUE THREAD

**Issue by LPUoO** [HenriquesLab/ZeroCostDL4Mic#49]
Hello,
I tried to make a new 2D model with N2V. For the training I had 5,152 images which made 30.2 GB.
In 3.1. (Setting main training parameters) I ran out of RAM.

I see here that I have 12,72 GB of RAM.
![image](https://user-images.githubusercontent.com/64419544/94377112-c458e300-0116-11eb-951b-235cf18dc188.png)

Does this mean that the maximum amount of training material has to be 12GB?

Thank you very much.

**Comment by guijacquemet** [comment]
Hi,
Yes, for N2V to train you need to be able to fit all your training patches to the runtime RAM. If you have such a large training dataset you could consider removing the data augmentation step which is enabled by default in N2V. This may help you fit everything to your RAM while keeping the diversity in your training data.
In Google Colab you may also get attributed 25GB of RAM (especially after a crash due to RAM overload) but it is not a sure thing.
Cheers

Guillaume

**Comment by LPUoO** [comment]
Hello @guijacquemet ,

I'm using N2V, this time in 3D and I'm running again into `out of ram` issues.
My starting material is 10 images (8-bit, 1024*1024 px, 70 slices in average). Total size 710 MB.

After step 3.1 (`setting main parameters`) it uses 3.67 GB of RAM
After step 4.1 (`create the model and dataset objects`) it uses 6.51 GB of RAM (44800 patches created)
During step 4.2 (`training`) it uses 22.48 GB of RAM.

This is without data augmentation.
Is this an expected behaviour?

Thank you very much

**Comment by guijacquemet** [comment]
Hi,

Yes it is. You are generating a lot of training patches here and using up all the RAM available in Colab.

To train in Colab you need to remove a few images from your training dataset.
Otherwise you can start thinking about using other platforms that provide more powerful training ressources.

For instance you can run the notebook locally: https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Running-notebooks-locally

Or using paid for online platforms:
https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki/Running-ZeroCostDL4Mic-notebooks-on-FloydHub

Cheers

Guillaume



On 29 Dec 2020 20:22, LPUoO <notifications@github.com> wrote:

Hello @guijacquemet<https://github.com/guijacquemet> ,

I'm using N2V, this time in 3D and I'm running again into out of ram issues.
My starting material is 10 images (8-bit, 1024*1024 px, 70 slices in average). Total size 710 MB.

After step 3.1 (setting main parameters) it uses 3.67 GB of RAM
After step 4.1 (create the model and dataset objects) it uses 6.51 GB of RAM (44800 patches created)
During step 4.2 (training) it uses 22.48 GB of RAM.

This is without data augmentation.
Is this an expected behaviour?

Thank you very much
