### ISSUE TITLE
Error when Training 3D Stardist

### ISSUE THREAD

**Issue by GionaKleinberg** [HenriquesLab/ZeroCostDL4Mic#57]
Hello,

I'm running into this error when attempting to train a model on the 3D stardist notebook. It occurs on the 4.2 Start Training step and I can't seem to figure out why. I'm using the default training parameters. I've tried readjusting the epochs and steps per epochs parameters but the error persists. Turning off data augmentation and restarting the kernel also seemed not to help. The training set is about 5 pairs of image stacks (about 16 slices per stack).

![image](https://user-images.githubusercontent.com/67409977/97326469-6a992500-184a-11eb-8a5c-bdfcb6623da9.png)

Is there a known cause of this error? Thanks

Best,
Giona

**Comment by guijacquemet** [comment]
Hi Giona,

Thanks a lot for reaching out! I have never seen this error before and I cannot reproduce it on my end. To help you out I would need a little bit more information.

- Could you confirm that you run the cell 3.1 after inputting the parameters? 
- Do you have the same error when using the demo data provided by the StarDist authors? (https://github.com/mpicbg-csbd/stardist/releases/download/0.3.0/demo3D.zip)
- Could you give me more information about your training dataset and how it was annotated? The dimension of the training images in pixel would especially be useful

Cheers

Guillaume

**Comment by uschmidt83** [comment]
Hi @GionaKleinberg, can you please click on the text "3 frames" (preceded by up/down arrow symbol) when this error happens? This will likely help to show the real cause of this.

Best,
Uwe

**Comment by GionaKleinberg** [comment]
@uschmidt83 Here is the full error message.
![image](https://user-images.githubusercontent.com/67409977/97815928-a45d9780-1c5f-11eb-8702-4556aaaf2e6b.png)


@guijacquemet I did run cell 3.1 as well as all the other necessary cells in order.
All the training images are 256,256,16 except for one that is 142,143,5. Based on the full error message, I removed the smaller one, and the training works but I'd like to be able to train using the 5 slice image as well. Is that possible or is it simply too small?

**Comment by uschmidt83** [comment]
> @uschmidt83 Here is the full error message.

Somebody recently had the same issue: https://github.com/mpicbg-csbd/stardist/issues/98
This small bug was due to `patch_size` being a `list` instead of a `tuple` (which happened after loading the config from disk).

It's an easy fix/workaround for now, and will be fixed in the next release of StarDist (more details: https://github.com/mpicbg-csbd/stardist/pull/97).

Best,
Uwe

**Comment by guijacquemet** [comment]
@GionaKleinberg 
In the notebook, if you use the default parameters, the patch size is automatically chosen to match the dimension of your images. However, currently, this reading is taken from a random image in your training folder. In your case, you could change the patch_size so that it matches the smallest dimension of your images. I have never tested to train StarDist3D using images of different dimension, but this may just work (@uschmidt83 would be able to advise about this). Let me know if it does. It would also be worth checking if you get a better model by including this image (and using a smaller patch size) or by excluding this image and using a larger patch size.

I hope this makes sense!

**Comment by uschmidt83** [comment]
https://stardist.net/docs/faq.html#which-size-should-the-training-images-be

**Comment by GionaKleinberg** [comment]
I ended up just removing the problematic images from the training set and setting the patch size to match the remaining images.  It didn't work keeping the image likely because of its very small size.
