### ISSUE TITLE
UNet issue training issue

### ISSUE THREAD

**Issue by CadotB** [HenriquesLab/ZeroCostDL4Mic#6]
I'm trying to use the U-net to segment IF images. I gave 16 images as training source and the same 16 images manually segmented as training target. 
Unfortunately, I got this when I start the training: 
![image](https://user-images.githubusercontent.com/62887684/77914035-93960f00-7295-11ea-95dc-fbed9d579e1f.png)
I'm totally novice in python. Do you know where I'm doing something wrong?
Thanks

**Comment by lucpaul** [comment]
Hi, this error seems to have to do with the image dimensions or image format. What size are your images? And what type of data is it? 
Ideally, your images should be square (so same number of pixels in x and y) and grayscale. Also, if possible, shape your images into dimensions that are divisible by 32, (how about 4000x4000?). 
The data we used were 8-bit .tif files. Don't use RGB images. If you can give a little bit more info on the data maybe I can help you more.

I hope this helps.

**Comment by CadotB** [comment]
Hi, Thanks for your answer. My images where 9246x9246 or 12302x12302, tif, 8 bit, from fluorescence. I crop them to have  4000x4000, and the training went further but didn't finished. Now I have:
![image](https://user-images.githubusercontent.com/62887684/77959293-a2e97c80-72d6-11ea-8a68-661f0adc7e17.png)
Here is one of them: https://drive.google.com/open?id=1e43rOatP113aXjYS8EXJcw2HpYAxmIEm
and its trained counterpart: https://drive.google.com/open?id=1YQ7kONFZvW3rGNA4qT1ljORRh9oK0kOJ
Thanks!

**Comment by lucpaul** [comment]
I see. This is annoying but I think you have very likely run into one of the limitations of colab that we also encountered and which is described in our preprint. This has to do with the size of the data. Simply put, your images are too big and when you try to load your data into your network colab can't handle it. What you can try is a) reduce the batch size (go down to 1) because that way the data loaded into the network is less at each time point or b) crop your data into smaller patches; this worked for us with 1024x1024 patches, but you can try 2048x2048 or any other size smaller than 4000, but maybe start low and work out the upper limit. 

This might be frustrating but is simply a limitation of the free service provided by the platform. I hope this helps you to figure it out.

**Comment by CadotB** [comment]
Thanks a lot, now it's working with 1024x1024 images. I will mosaic my images to this size to make things easier.

**Comment by lucpaul** [comment]
Great. I will close this now then. Feel free to open again if something else on this arises.
