### ISSUE TITLE
Transfer Learning

### ISSUE THREAD

**Issue by econdesousa** [HenriquesLab/ZeroCostDL4Mic#68]
Hi 
Thanks for your fantastic job!!!

Can you please explain me how can I train one of your models on the datasets you provide and then use it as transfer learning with my (smaller) datasets?
Do you have any notebooks already prepared or tutorials I can follow to edit the original notebooks?
Thanks

**Comment by guijacquemet** [comment]
Hi,

Could you give us a little bit more details on what you want to do? that way we can give you more specifics answers.

In short, you can perform transfer learning in all our notebooks by just choosing the model you want to use as a starting point for your training session. See section 3.3 of the notebooks.

**Comment by econdesousa** [comment]
Ok, thanks...

I missed that section's purpose... Sorry about that.

Let me please add two other related questions (I'm not sure if these are valid for all your notebooks, but they are, at least, for the stardist2D/3D). In section 3.1 you ask for configuration folders (datafolders, path and name of the model to save, ...); then, in 3.2 you ask for data augmentation; and finally in 3.3 you ask if I want to use as staring point the weights from pretrained models. My questions are:

1. Can I skip 3.1 and 3.2 and select the pretrained model and run the prediction on my data (I know it wouldn't be perfect - it would be better to train on my data but sometimes we simply don't have enough labeled data).
2. In your models you have a link to datasets. Retrain on those is somehow useful? I mean, I imagine that the data there is the same you used for the pretrained model, right? So, by using it again is the equivalent to add some more epochs, but nothing significantly better will result from that, right?

Thanks

**Comment by guijacquemet** [comment]
Hi,

To answer your questions:

**Can I skip 3.1 and 3.2 and select the pretrained model and run the prediction on my data (I know it wouldn't be perfect - it would be better to train on my data but sometimes we simply don't have enough labeled data).**

No, you cannot use the notebook in this way. If you want to make a prediction directly without training, check the excellent Fiji StarDist plugin that comes directly with trained models (https://imagej.net/StarDist). 
Alternatively, it is possible to load these StarDist 2D models to make predictions in Google Colab, but for that, you would need to modify the code to load these specific models. 
Otherwise, you can check our Cellpose notebook that allows you to use the Cellpose models in absence of training.

**In your models you have a link to datasets. Retrain on those is somehow useful? I mean, I imagine that the data there is the same you used for the pretrained model, right? So, by using it again is the equivalent to add some more epochs, but nothing significantly better will result from that, right?**

Again no, the dataset we provide are test datasets so that users can learn how to use the various notebooks. We do not actually provide pretrained models based on these datasets directly in the notebooks (some of them are available on Zenodo). The pretrained models already available for transfer learning in the StarDist and Cellpose notebooks are the models made available by the StarDist and Cellpose teams. These models are likely more "generalisable" as they were trained on more  (and different data).

**Comment by econdesousa** [comment]
Thanks

**Comment by alievakrash** [comment]
Hi, I was wondering if the transfer learning option is only available for Stardist? I was checking for 3D UNET and could not find it.
