### ISSUE TITLE
Use Stardist3D on ImageJ

### ISSUE THREAD

**Issue by econdesousa** [HenriquesLab/ZeroCostDL4Mic#75]
Hi

I was training a Stardist3D model. For now I just downloaded the datasets from the link https://github.com/HenriquesLab/ZeroCostDL4Mic/wiki and run all the notebook. It already performed quite well on my data but my intention is to train it better on my own 3d datasets.

Now I have a model saved at my google drive, is it possible to somehow run the predictions directly from within ImageJ (through DeepImageJ, CSBDeep, ...) to speedup my workflows? 

Thanks

**Comment by guijacquemet** [comment]
Hi,

As far as I know, it is currently not possible to run StarDist3D models in ImageJ. The StarDist Fiji plugin only performs prediction for 2D datasets or 2D + t. That said you may want to check how well StarDist 2D +t is performing on your data. You can then merge consecutive detection into 3D objects as described here: https://forum.image.sc/t/call4help-3d-dense-nuclei-segmentation-challenge/23462/21

Perhaps it is possible to export StarDist models so that they could be used in CSBdeep or  DeepImageJ, but if it possible is not currently implemented in our notebook. 

I hope this helps!

Cheers

Guillaume

**Comment by econdesousa** [comment]
Hi

I'll try the 2D+t version. In fact my datasets have a limited number of z-slices... so that may work!!!

Thanks
