### ISSUE TITLE
YOLOv2 Step 3 " IndexError: list index out of range" Error using makesense.ai dataset

### ISSUE THREAD

**Issue by wakabayashi-kt** [HenriquesLab/ZeroCostDL4Mic#94]
Hello!

While playing Step 3 in YOLOv2 after defining my paths and uploading my training source image and training source annotation xml generated by makesense.ai, I am encountering the following error:

---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-12-5b897921ef2f> in <module>()
    113 os.mkdir(full_model_path)
    114 
--> 115 pdf_export()

<ipython-input-10-daa551ff8665> in pdf_export(trained, augmentation, pretrained_model)
   1003   #print(gpu_name)
   1004 
-> 1005   shape = io.imread(Training_Source+'/'+os.listdir(Training_Source)[1]).shape
   1006   dataset_size = len(os.listdir(Training_Source))
   1007 

IndexError: list index out of range

I have managed once to get past this stage and train a model successfully, but have not been successful since.

I am running Windows 10, and using Chrome at the moment. Is there something I'm doing wrong?

Thanks!

Ken

**Comment by guijacquemet** [comment]
Hi,
Thanks for reaching out! And glad that you already found where your issue comes from!. 
Yes, you will need several images to be able to train YOLO. Not sure what the minimum actually is and @lucpaul may be able to help here. 
But you will need at least 2 as you will need one image for training and another for validation (used during training). 

Cheers
Guillaume
