### ISSUE TITLE
fnet - Overwriting existing model name Section 3.1

### ISSUE THREAD

**Issue by dimi-huer** [HenriquesLab/ZeroCostDL4Mic#97]
**Describe the bug**
The variable _W_ is called here without the possibility to assign it.

https://github.com/HenriquesLab/ZeroCostDL4Mic/blob/0ee9a5b24a18a64bd02f6c25a320500422438653/Colab_notebooks/fnet_ZeroCostDL4Mic.ipynb#L779

Additionally if variable _W_ is removed, there is another warning referencing to section 3.3:

> !! WARNING: _model_name_ already exists and will be deleted in the following cell !!
To continue training _model_name_, choose a new model_name here, and load _model_name_ in section 3.3
RUN_DIR="saved_models/${DATASET}"

**To Reproduce**
1. Run the fnet notebook until section 3.1
2. Choose an already existing model name in the same path.
3. Run the cell in section 3.1

**Expected behavior**
A section 3.3 where it is possible to change the model name or a displayed warning should change.

**Comment by lucpaul** [comment]
Hi, yes, this was a bug caused by a typo and the reference to 3.3. was also wrong. 

I have now updated the fnet notebook to remove this error. Also the notebook now correctly overwrites any previously named models before training instead of in the parameter cell. This means that in case you put in a previously named model by accident, it won't be immediately overwritten, but the error can be corrected by the user before training. I only noticed this thanks to the comment. So thanks for that.

Have a look yourself and see if the notebook stops doing this and that the warning message makes more sense now.
